spring:
  application:
    name: crud

  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true

server:
  port: 9001

jwt:
  auth:
    converter:
      resource-id: spring-cloud-gateway-client
      principle-attribute: preferred_username

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



